chats/urls.py
from django.urls import path
from .views import ChatView, ChatDeleteView, ChatUpdateView

urlpatterns = [
    path('chat/<int:pk>/edit/', ChatUpdateView.as_view(), name='chat_edit'),
    path('chat/<int:pk>/delete/', ChatDeleteView.as_view(), name='chat_delete'),
    path('chat/', ChatView.as_view(), name='chat'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chats.urls')),
    path('', include('job.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

job/urls.py
from django.urls import path
from .views import JobListView, JobUpdateView, JobDeleteView, JobDetailView, JobCreateView, RegionListView, HomeView, RegionDetailView, MyJobListView
from . import views

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('user_job_list/<str:username>/', MyJobListView.as_view(), name='user_job_list'),
    path('region/<int:pk>/', RegionDetailView.as_view(), name='region_detail'),
    path('regions/', RegionListView.as_view(), name='region_list'),
    path('job_list/', JobListView.as_view(), name='job_list'),
    path('job/<int:pk>/edit/', JobUpdateView.as_view(), name='job_edit'),
    path('job/<int:pk>/delete/', JobDeleteView.as_view(), name='job_delete'),
    path('job/<int:pk>/', JobDetailView.as_view(), name='job_detail'),
    path('job/new', JobCreateView.as_view(), name='job_new'),
    path('city_id/<int:region_id>/', views.get_cities, name='city_id'), #viloyatni tanlaganda shahar chiqishi uchun. JavaScript uchun

]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=20, blank=False, null=False)
    telegram = models.CharField(max_length=500, blank=True, null=True)

chats/models.py
from django.conf import settings
from django.db import models

class ChatMessage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.user.username} - {self.timestamp}"

job/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

class Region(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Job(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    salary = models.CharField(max_length=10)
    salary_period = models.CharField(max_length=10,
                                     choices=[('hourly', 'Soatlik'), ('daily', 'Kunlik'), ('weekly', 'Haftalik'),
                                              ('monthly', 'Oylik')], blank=False, null=False)
    start_time = models.TimeField(default="08:00")
    end_time = models.TimeField(default="18:00")
    phone_number = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    address = models.CharField(max_length=255)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('job_detail', args=[str(self.id)])

chats/forms.py
from django import forms
from .models import ChatMessage

class ChatForm(forms.ModelForm):
    class Meta:
        model = ChatMessage
        fields = ['message']

chats/views.py
import time
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from .models import ChatMessage
from .forms import ChatForm
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class ChatView(LoginRequiredMixin, View):
    template_name = 'chat.html'

    def get(self, request):
        chat_messages = ChatMessage.objects.all().order_by('-timestamp')[:50]

        last_message_time = request.session.get('last_message_time')
        current_time = time.time()

        if last_message_time is None or current_time - last_message_time > 1:
            can_post = True
        else:
            can_post = False

        chat_form = ChatForm()

        context = {
            'chat_messages': chat_messages,
            'chat_form': chat_form,
            'can_post': can_post,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        chat_messages = ChatMessage.objects.all().order_by('-timestamp')[:50]

        last_message_time = request.session.get('last_message_time')
        current_time = time.time()

        if last_message_time is None or current_time - last_message_time > 1:
            can_post = True
        else:
            can_post = False

        chat_form = ChatForm(request.POST)

        if can_post and chat_form.is_valid():
            new_message = chat_form.save(commit=False)
            user_id = request.user.id
            last_message = get_last_message(user_id)

            if last_message is None or last_message.message != new_message.message:
                new_message.user = request.user
                new_message.save()
                chat_form = ChatForm()  # To clear the form after submission
                request.session['last_message_time'] = current_time

        context = {
            'chat_messages': chat_messages,
            'chat_form': chat_form,
            'can_post': can_post,
        }
        return render(request, self.template_name, context)

def get_last_message(user_id):
    try:
        return ChatMessage.objects.filter(user_id=user_id).latest('timestamp')
    except ChatMessage.DoesNotExist:
        return None



class ChatDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ChatMessage
    template_name = 'chat_delete.html'
    success_url = reverse_lazy('chat')

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user or self.request.user.is_superuser

class ChatUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ChatMessage
    template_name = 'chat_edit.html'
    fields = ('message',)
    success_url = reverse_lazy('chat')

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user or self.request.user.is_superuser

templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
    <html lang="uz">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Iconkalar ulandi -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&family=Roboto+Mono:wght@300&display=swap"
          rel="stylesheet">


    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous"></script>
    <title>AlbaUz.com</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<!-- header qismi start -->
<div class="container-fluid">
    <div class="row">
        <div class="col p-0 mb-1">
            <!-- Navbar start -->
            <nav class="center navbaruz h4">

                {% if request.path == "/" or 'region/' in request.path and region.pk or 'job/' in request.path and job.pk %}
                    <select class="selectuz" style="width:175px; height:40px;" id="regionSelect" class="form-select"
                            onchange="redirectToRegionDetail(this.value)">
                        {% if request.path == "/" %}
                            <option value="" disabled selected>Viloyat</option>
                        {% else %}
                            {% if region.name %}
                                <option value="" disabled selected>{{ region.name }}</option>
                            {% else %}
                                <option value="" disabled selected>{{ job.region }}</option>
                            {% endif %}

                        {% endif %}
                        {% for region in regions %}
                            <option value="{{ region.pk }}">{{ region.name }}</option>
                        {% endfor %}
                    </select>
                {% else %}
                    {% block title %}{% endblock title %}
                {% endif %}

                {% if 'region/' in request.path and region.pk %}
                    <select class="selectuz" style="width:175px; height:40px;" aria-label="Default" id="id_city"
                            name="city">
                        <option value="">Shahar</option>
                        {% for city in region.city_set.all %}
                            <option value="{{ city.pk }}">{{ city.name }}</option>
                        {% endfor %}
                    </select>
                {% endif %}


                <script>
                    function redirectToRegionDetail(regionId) {
                        if (regionId !== "") {
                            var url = "{% url 'region_detail' 0 %}".replace('0', regionId);
                            window.location.href = url;
                        }
                    }
                </script>


            </nav>
            <!-- Navbar stop -->
        </div>
    </div>
</div>


<!--SIDEBAR YANGI-->
<style>
    /* Sidebar o'lchamini 250 piksellikga kichraytirish */
    .offcanvas {
        width: 360px !important;
    }
</style>
<div class="offcanvas offcanvas-start bg-dark" tabindex="-1" id="offcanvasExample"
     aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <form class="d-flex" role="search">
            <style>
                .form-control {
                    width: 180px; /* Element kengligi */
                    height: 30px; /* Element bo'yligi */
                }
            </style>
            <input class="form-control me-2" type="search" placeholder="Qidirish" aria-label="Search">
            <button class="btn btn-outline-warning activeuz" type="submit">Qidirish</button>
        </form>
        <style>
            /* Tugma rangini oq qilish */
            .btn-close {
                color: #ffffff; /* Matn rangi */
                background-color: #ffffff; /* Tugma fon rangi */
                border-color: #ffffff; /* Tugma chegarasining rangi */
            }
        </style>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body bg-dark">

        <!-- Bu yer sidebar qismining ichi -->
    </div>
</div>
<!-- Sidebar yangi tugadi -->

<!-- Kontener qismi boshlandi -->
<div class="container-fluid">
    <div class="row">
        <!-- Sidebar qismi tugadi -->

        <!-- Mainbar qismi boshlandi -->
        <div class="col-12 mainBaruz">

            {% block content %}
            {% endblock content %}

        </div>
        <!-- Mainbar tugadi -->
    </div>
</div>
<!-- Kontener tugadi -->


<!-- footer qismi boshlandi -->

<div class="d-block" style="padding-top: 70px"></div>
<div class="bg-dark text-center border-top fixed-bottom">
    <div class="container">
        <div class="row">
            <style>
                /* Ikonning rangini oq qilish */
                .icon path {
                    fill: #ffffff; /* Oq rang */
                }
            </style>
            <div class="col">
                <a class="nav-panel" href="/">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="icon">
                        <path d="M23.121,9.069,15.536,1.483a5.008,5.008,0,0,0-7.072,0L.879,9.069A2.978,2.978,0,0,0,0,11.19v9.817a3,3,0,0,0,3,3H21a3,3,0,0,0,3-3V11.19A2.978,2.978,0,0,0,23.121,9.069ZM15,22.007H9V18.073a3,3,0,0,1,6,0Zm7-1a1,1,0,0,1-1,1H17V18.073a5,5,0,0,0-10,0v3.934H3a1,1,0,0,1-1-1V11.19a1.008,1.008,0,0,1,.293-.707L9.878,2.9a3.008,3.008,0,0,1,4.244,0l7.585,7.586A1.008,1.008,0,0,1,22,11.19Z"></path>
                    </svg>
                    <span class="text-light"> Home </span>
                </a>
            </div>

            <div class="col my-auto">
                <a class="nav-panel" href="{% url 'job_new' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" style="width: 25px; height: 25px;" viewBox="0 0 24 24"
                         class="" stroke-width="2" stroke="white" fill="none" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M9 12h6"></path>
                        <path d="M12 9v6"></path>
                        <path d="M12 3c7.2 0 9 1.8 9 9s-1.8 9 -9 9s-9 -1.8 -9 -9s1.8 -9 9 -9z"></path>
                    </svg>
                    <span class="text-light">New </span>
                </a>
            </div>
            <div class="col">
                <a class="nav-panel" href="{% url 'chat' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="icon">
                        <path d="M24,16v5a3,3,0,0,1-3,3H16a8,8,0,0,1-6.92-4,10.968,10.968,0,0,0,2.242-.248A5.988,5.988,0,0,0,16,22h5a1,1,0,0,0,1-1V16a5.988,5.988,0,0,0-2.252-4.678A10.968,10.968,0,0,0,20,9.08,8,8,0,0,1,24,16ZM17.977,9.651A9,9,0,0,0,8.349.023,9.418,9.418,0,0,0,0,9.294v5.04C0,16.866,1.507,18,3,18H8.7A9.419,9.419,0,0,0,17.977,9.651Zm-4.027-5.6a7.018,7.018,0,0,1,2.032,5.46A7.364,7.364,0,0,1,8.7,16H3c-.928,0-1-1.275-1-1.666V9.294A7.362,7.362,0,0,1,8.49,2.018Q8.739,2,8.988,2A7.012,7.012,0,0,1,13.95,4.051Z"></path>
                    </svg>
                    <span class="text-light"> Chat </span>
                </a>
            </div>
            <div class="col">
                {% if user.is_authenticated %}
                    <a class="nav-panel position-relative" href="{% url 'user_profile' user.pk %}">
                {% else %}
                    <a class="nav-panel position-relative" href="{% url 'login' %}">
                {% endif %}


                {% if user.is_authenticated %}
                    <svg xmlns="http://www.w3.org/2000/svg" fill="lightskyblue">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                        <path fill-rule="evenodd"
                              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
                    </svg>
                    <span style="color: lightskyblue ">{{ user.username }}</span>
                {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                        <path fill-rule="evenodd"
                              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
                    </svg>
                    <span class="text-light">
                            Profile
                        </span>
                {% endif %}

                </a>
            </div>
        </div>
    </div>
</div>


</body>
</html>

templates/chat_delete.html
{% extends 'base.html' %}
{% block title %}O'chirish{% endblock title %}

{% block content %}
    <h1>Postni o'chirish</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">O'chirish</button>
    </form>
{% endblock content %}

templates/chat_edit.html
{% extends 'base.html' %}
{% block title %}O'zgartirish{% endblock title %}

{% block content %}
    <h1>Postni o'zgartirish</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">O'zgartirish</button>
    </form>
{% endblock content %}

templates/job_new.html
{% extends 'base.html' %}
{% block title %}Saytga ish joylash{% endblock title %}


{% block content %}
    <div class="list-group marginuz">
        <div class="list-group-item bg-detail text-dark">
            {% if form.errors %}
                <div class="alert alert-danger mt-3">
                    <ul>
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <label for="id_name" class="form-label">Ish nomi</label>
                <input class="form-control inputuz" type="text" id="id_name" name="name">
                <br>
                <label class="form-label" for="id_salary">To'lanadigan haq (won)</label><br>
                <select class="form-select inputuz" name="salary_period" id="id_salary_period">
                    <option value="monthly">Oylik</option>
                    <option value="weekly">Haftalik</option>
                    <option value="daily">Kunlik</option>
                    <option value="hourly">Soatlik</option>
                </select><br>
                <input class="form-control inputuz" placeholder="170.000" type="text" id="id_salary" name="salary">
                <br>
                <label class="form-label" for="id_start_time">Boshlash vaqti</label>
                <input class="form-control inputuz" type="time" id="id_start_time" name="start_time" value="08:00">
                <br>
                <label class="form-label" for="id_end_time">Tugash vaqti</label>
                <input class="form-control inputuz" type="time" id="id_end_time" name="end_time" value="18:00">
                <br>
                <label class="form-label" for="id_phone_number">Telefon raqam</label>
                <input class="form-control inputuz" type="text" id="id_phone_number" value="{{ user.phone_number }}"
                       name="phone_number">
                <br>
                <label class="form-label" for="id_address">Manzil</label>
                <input class="form-control inputuz" type="text" id="id_address" name="address">
                <br>
                <label class="form-label " for="id_region">Viloyat</label>
                <select class="form-select inputuz" aria-label="Default" id="id_region" name="region">
                    <option value="">----------</option>
                    {% for region in regions %}
                        <option value="{{ region.pk }}">{{ region.name }}</option>
                    {% endfor %}
                </select>
                <br>
                <label class="form-label" for="id_city">Shahar</label>
                <select class="form-select inputuz" aria-label="Default" id="id_city" name="city">
                    <option value="">----------</option>
                </select>
                <br>
                <label class="form-label" for="id_description">Ish haqida qo'shimcha ma'lumotlar</label><br>
                <textarea class="form-control" style="width: 300px; height: 200px;" id="id_description"
                          name="description"></textarea>
                <br>
                <button class="btn btn-primary" type="submit">Joylash</button>
            </form>
        </div>
    </div>




    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_region').change(function () {
                var regionId = $(this).val();
                if (regionId) {
                    $.ajax({
                        url: '/city_id/' + regionId + '/',
                        type: 'GET',
                        dataType: 'json',
                        success: function (data) {
                            var citySelect = $('#id_city');
                            citySelect.empty();
                            if (data.length > 0) {
                                $.each(data, function (key, value) {
                                    citySelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                                });
                            } else {
                                citySelect.append('<option value="">----------</option>');
                            }
                        }
                    });
                } else {
                    $('#id_city').empty();
                }
            });
        });
    </script>



{% endblock %}

templates/region_detail.html
{% extends 'base.html' %}

{% block title %}{{ region.name }}{% endblock title %}

{% block content %}

    {% for job in jobs %}
        <div class="list-group marginuz job-item" data-city-id="{{ job.city.pk }}">
            <a href="{% url 'job_detail' job.pk %}" class="list-group-item bg-detail text-dark my-link-hover2">
                <b>{{ job.name }}</b>
                <hr>
                <p class="fw-light">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-cash-coin" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                              d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"></path>
                        <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"></path>
                        <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"></path>
                        <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"></path>
                    </svg>
                    {% if job.salary_period == 'monthly' %}
                        Oylik
                    {% elif job.salary_period == 'weekly' %}
                        Haftalik
                    {% elif job.salary_period == 'daily' %}
                        Kunlik
                    {% elif job.salary_period == 'hourly' %}
                        Soatlik
                    {% endif %}
                    : {{ job.salary }} won<br>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-geo-alt"
                         viewBox="0 0 16 16">
                        <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z"></path>
                        <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"></path>
                    </svg>
                    Shahar: {{ job.city }}</p>
                <span class="small-right text-secondary fw-light">
                {{ job.date|date:"d-F, H:i" }}
            </span>
            </a>
        </div>
    {% endfor %}

    {% if not jobs %}
        <div class="list-group marginuz">
            <div class="list-group-item bg-detail text-dark">
                <b>Bu viloyatda hozircha ishlar yo'q!</b><br> Iltimos ish joylanganini vaqti vaqti bilan tekshirib
                turing! InshaAllah ish chiqib qolar...
            </div>
        </div>
    {% endif %}

    <!-- Pagination -->

    <div class="list-group marginuz">
        <div class="list-group-item bg-detail text-dark">
            <nav aria-label="Page navigation example ">
                <ul class="pagination pt-4">
                    {% if jobs.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ jobs.previous_page_number }}">&laquo;
                            orqaga</a></li>
                    {% endif %}

                    {% for page_number in jobs.paginator.page_range %}
                        <li class="page-item {% if page_number == jobs.number %}active{% endif %}">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% endfor %}

                    {% if jobs.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ jobs.next_page_number }}">oldinga
                            &raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>




    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_region').change(function () {
                var regionId = $(this).val();
                if (regionId) {
                    $.ajax({
                        url: '/city_id/' + regionId + '/',
                        type: 'GET',
                        dataType: 'json',
                        success: function (data) {
                            var citySelect = $('#id_city');
                            citySelect.empty();
                            if (data.length > 0) {
                                $.each(data, function (key, value) {
                                    citySelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                                });
                            } else {
                                citySelect.append('<option value="">----------</option>');
                            }
                        }
                    });
                } else {
                    $('#id_city').empty();
                }
            });

            $('#id_city').change(function () {
                var selectedCityId = $(this).val();
                $('.job-item').hide();
                $('.job-item[data-city-id="' + selectedCityId + '"]').show();
            });
        });
    </script>
{% endblock content %}

templates/user_profile_update.html
{% extends 'base.html' %}
{% block title %}Ma'lumotlarni o'zgartirish{% endblock title %}

{% block content %}
    <div class="list-group marginuz">
        <div class="list-group-item bg-detail text-dark">
            <form method="post">{% csrf_token %}

                <label class="form-label" for="id_username">Login</label>
                <input class="form-control inputuz" type="text" name="username" value="{{ user.username }}"
                       maxlength="150" required id="id_username">
                <br>
                <label class="form-label" for="id_last_name">Familiyangiz</label>
                <input class="form-control inputuz" type="text" name="last_name" value="{{ user.last_name }}" maxlength="150"
                       id="id_last_name">
                <br>
                <label class="form-label" for="id_first_name">Ismingiz</label>
                <input class="form-control inputuz" type="text" name="first_name" value="{{ user.first_name }}"
                       maxlength="150" id="id_first_name">
                <br>
                <label class="form-label" for="id_email">Email</label>
                <input class="form-control inputuz" type="email" name="email" value="{{ user.email }}" maxlength="254"
                       id="id_email">
                <br>
                <label class="form-label" for="id_phone_number">Telefon</label>
                <input class="form-control inputuz" type="text" name="phone_number" value="{{ user.phone_number }}" maxlength="20"
                       required
                       id="id_phone_number">
                <br>
                <label class="form-label" for="id_telegram">BIO</label>
                <input class="form-control inputuz" type="text" name="telegram" value="{{ user.telegram }}" maxlength="500"
                       id="id_telegram">
                <br>
                <button class="btn btn-primary" type="submit">O'zgartirish</button>
            </form>
        </div>
    </div>
{% endblock content %}